In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/__init__.py'>

In [3]:
data = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
data = np.array(data) #ndArray로 생성 

In [7]:
data.dtype

dtype('int64')

In [8]:
data + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
data * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [11]:
data **3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [12]:
data / 10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])